# Generated by Django 3.0.6 on 2023-04-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('doa', models.DateField()),
                ('semester', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('age', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('amount', models.CharField(max_length=100)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.PositiveIntegerField()),
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regno_Student_set', to='cl.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mregno_Student_set', to='cl.Admission')),
            ],
        ),
    ]
